[package]
name = "abi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ts-rs = "6.0"
js-sys = "0.3.55"
serde = { version = "1.0", features = ["derive"] }
